### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by peisenha** [HumanCapitalAnalysis/seminar#2]
https://github.com/HumanCapitalAnalysis/seminar/blob/master/slides_guests/Introduction_python.pdf

Please fix.

**Comment by vstottuth** [comment]
The pdf can be found under a slightly different link:
https://github.com/HumanCapitalAnalysis/seminar/blob/master/guest_lectures/Introduction_python.pdf
I updated it in our seminar Readme from last semester
